schema = 3

[mod]
  [mod.'github.com/Masterminds/goutils']
    version = 'v1.1.1'
    hash = 'sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY='

  [mod.'github.com/Masterminds/semver/v3']
    version = 'v3.2.1'
    hash = 'sha256-VKHIquwriyOL8A0qgtmap/3cGEOpDokOLtPg1w4xjMA='

  [mod.'github.com/Masterminds/sprig/v3']
    version = 'v3.2.3'
    hash = 'sha256-1GLZic3WQIBZGyjvyHbfcZ/7EV7oNzNhkwEiiTpVfL4='

  [mod.'github.com/armon/go-radix']
    version = 'v1.0.0'
    hash = 'sha256-A5SNdGtw8I6ngk9U3p+rKu6KB7inSngqmdnJl74EM9Q='

  [mod.'github.com/bgentry/speakeasy']
    version = 'v0.1.0'
    hash = 'sha256-Gt1vj6CFovLnO6wX5u2O4UfecY9V2J9WGw1ez4HMrgk='

  [mod.'github.com/fatih/color']
    version = 'v1.16.0'
    hash = 'sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ='

  [mod.'github.com/google/go-cmp']
    version = 'v0.6.0'
    hash = 'sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg='

  [mod.'github.com/google/uuid']
    version = 'v1.4.0'
    hash = 'sha256-FU0gzLmS48Ik9T+quGg5z/7ESGMPSXM3SY+rdJtG+5w='

  [mod.'github.com/hashicorp/cli']
    version = 'v1.1.6'
    hash = 'sha256-/rcjznXypJYwDLDAQ4G7hFkeugXRNx0XSftGK76Js5E='

  [mod.'github.com/hashicorp/errwrap']
    version = 'v1.1.0'
    hash = 'sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw='

  [mod.'github.com/hashicorp/go-multierror']
    version = 'v1.1.1'
    hash = 'sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA='

  [mod.'github.com/hashicorp/terraform-plugin-codegen-spec']
    version = 'v0.2.0'
    hash = 'sha256-3r7mQu3lIT+XXRcLrmygpOcBIlLyZO0BIfUs1ADUpms='

  [mod.'github.com/huandu/xstrings']
    version = 'v1.4.0'
    hash = 'sha256-lw0qFsUNW6ZPXNwawpUSfJQjZ+/PKMLkC/yW64t1yng='

  [mod.'github.com/imdario/mergo']
    version = 'v0.3.16'
    hash = 'sha256-gh2TEAq8YrZOEAf6SFW4AIcEEUguD68G+7/VUnBeWwM='

  [mod.'github.com/mattn/go-colorable']
    version = 'v0.1.13'
    hash = 'sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mitchellh/copystructure']
    version = 'v1.2.0'
    hash = 'sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc='

  [mod.'github.com/mitchellh/reflectwalk']
    version = 'v1.0.2'
    hash = 'sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s='

  [mod.'github.com/posener/complete']
    version = 'v1.2.3'
    hash = 'sha256-/17KFHD0SsGALg9iLXNIdvVFcotOO+H6bOOD5SY0MVs='

  [mod.'github.com/shopspring/decimal']
    version = 'v1.3.1'
    hash = 'sha256-MA3RmMQKPrposbqXcHdvAJL50O1WsIe0EBd7rMSWPPA='

  [mod.'github.com/spf13/cast']
    version = 'v1.5.1'
    hash = 'sha256-/tQNGGQv+Osp+2jepQaQe6GlncZbqdxzSR82FieiUBU='

  [mod.'github.com/stretchr/testify']
    version = 'v1.7.2'
    hash = 'sha256-ITCzt75vwTtQqHrkCEQtiYMfdmkUd+bIQVX18cg5kns='

  [mod.'github.com/xeipuuv/gojsonpointer']
    version = 'v0.0.0-20190905194746-02993c407bfb'
    hash = 'sha256-/u+qznDY8cnECZYIgSMRpKVWs04yAkW6EoGhqt+t73g='

  [mod.'github.com/xeipuuv/gojsonreference']
    version = 'v0.0.0-20180127040603-bd5ef7bd5415'
    hash = 'sha256-ZbXA+ASQrTgBQzasUKC9vznrOGpquYyWr+uwpm46fvU='

  [mod.'github.com/xeipuuv/gojsonschema']
    version = 'v1.2.0'
    hash = 'sha256-1ERBEvxj3pvHkMS2mvmvmYRi8jgAaTquo5hwjDLAEdc='

  [mod.'golang.org/x/crypto']
    version = 'v0.17.0'
    hash = 'sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0='

  [mod.'golang.org/x/sys']
    version = 'v0.15.0'
    hash = 'sha256-n7TlABF6179RzGq3gctPDKDPRtDfnwPdjNCMm8ps2KY='
