schema = 3

[mod]
  [mod.'github.com/Azure/azure-sdk-for-go/sdk/azcore']
    version = 'v1.18.1'
    hash = 'sha256-4RKd3uBAfAsfhemB2uLHSjaPiz5VU2ghL1uB9CCv/tE='

  [mod.'github.com/Azure/azure-sdk-for-go/sdk/azidentity']
    version = 'v1.10.1'
    hash = 'sha256-+ZZ171FX7dLxTk/8lW6xLAaBSha3IH0duR93whj0+hs='

  [mod.'github.com/Azure/azure-sdk-for-go/sdk/internal']
    version = 'v1.11.1'
    hash = 'sha256-mkxB/Yl3dI7NT2Tept8JEtM8qeFgiN/7B33KBhXNF7E='

  [mod.'github.com/Azure/entrauth']
    version = 'v0.0.0-20250819004238-dc2a3f58cbb7'
    hash = 'sha256-dItrNGlFlw+9xxkeYfFff8PNEAL1VcuQtS5VjgzvDWI='

  [mod.'github.com/AzureAD/microsoft-authentication-library-for-go']
    version = 'v1.4.2'
    hash = 'sha256-7Q6WJaWq/uYhEVXrSodXUQO4peJx7VJDtOlK1UlDTJ8='

  [mod.'github.com/ProtonMail/go-crypto']
    version = 'v1.1.6'
    hash = 'sha256-XlFT3uxgpPYFTND54uO8fH33jtQqAHWa7zrv24nw/PE='

  [mod.'github.com/agext/levenshtein']
    version = 'v1.2.2'
    hash = 'sha256-U+4DBwGWfKCr89Mx2eTZCWpaaRRrcn4qyRA1Pn61lag='

  [mod.'github.com/ahmetb/go-linq']
    version = 'v3.0.0+incompatible'
    hash = 'sha256-4eqUd+Z3ERABrkn53xtpWncRktdO61Zx8JLZXIrD51k='

  [mod.'github.com/apparentlymart/go-textseg/v15']
    version = 'v15.0.0'
    hash = 'sha256-960kVVQSGhx1Gww5cfoNeM3yXaA4dwlv+AFhKh6EGlA='

  [mod.'github.com/cloudflare/circl']
    version = 'v1.6.3'
    hash = 'sha256-XZm4EastgX67Dgm5BpOEW/PY4aLcHM/O8+Xbz26PuTY='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/fatih/color']
    version = 'v1.16.0'
    hash = 'sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ='

  [mod.'github.com/golang-jwt/jwt/v5']
    version = 'v5.2.2'
    hash = 'sha256-C0MhDguxWR6dQUrNVQ5xaFUReSV6CVEBAijG3b4wnX4='

  [mod.'github.com/golang/protobuf']
    version = 'v1.5.4'
    hash = 'sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/hashicorp/errwrap']
    version = 'v1.0.0'
    hash = 'sha256-LGSLrefkABG1kH1i+GUWiD2/ggJxiZEJ+D2YNbhZjmo='

  [mod.'github.com/hashicorp/go-checkpoint']
    version = 'v0.5.0'
    hash = 'sha256-QZe6mSoWT4M3B8BGlslHr/1eLrYfzvHhhmHQ69m0QLw='

  [mod.'github.com/hashicorp/go-cleanhttp']
    version = 'v0.5.2'
    hash = 'sha256-N9GOKYo7tK6XQUFhvhImtL7PZW/mr4C4Manx/yPVvcQ='

  [mod.'github.com/hashicorp/go-cty']
    version = 'v1.5.0'
    hash = 'sha256-VBeBGhqfUaVEz3k5JpLW9LInN/KVWFKqaSoS89/SlL8='

  [mod.'github.com/hashicorp/go-hclog']
    version = 'v1.6.3'
    hash = 'sha256-BK2s+SH1tQyUaXCH4kC0/jgqiSu638UFbwamfKjFOYg='

  [mod.'github.com/hashicorp/go-multierror']
    version = 'v1.1.1'
    hash = 'sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA='

  [mod.'github.com/hashicorp/go-plugin']
    version = 'v1.7.0'
    hash = 'sha256-nPTlKEssbp3/uDRZ2kkdO8z5mbu3j417Bra4FpBceHk='

  [mod.'github.com/hashicorp/go-retryablehttp']
    version = 'v0.7.7'
    hash = 'sha256-XZjxncyLPwy6YBHR3DF5bEl1y72or0JDUncTIsb/eIU='

  [mod.'github.com/hashicorp/go-set/v3']
    version = 'v3.0.1'
    hash = 'sha256-eJJ631I1KvVRodPTFAk6sBBJ3WDntPp+9AP3PiBjeYA='

  [mod.'github.com/hashicorp/go-uuid']
    version = 'v1.0.3'
    hash = 'sha256-8893qBbaug2yhxElowSrl3PrfhYlQ7cZ71QBgZWqpHE='

  [mod.'github.com/hashicorp/go-version']
    version = 'v1.7.0'
    hash = 'sha256-Umc/Q2mxRrPF4aEcDuDJq4lFBT+PSsnyANfyFwUIaxI='

  [mod.'github.com/hashicorp/hc-install']
    version = 'v0.9.2'
    hash = 'sha256-13B7tfg2ReQixXuFBXcENL6Nj22A6aAP8VCDh7xsaAI='

  [mod.'github.com/hashicorp/hcl/v2']
    version = 'v2.24.0'
    hash = 'sha256-jITSl/3Ep8ID0uQSzXK1mxCoi7r/Dq2SPSvVyS/nU10='

  [mod.'github.com/hashicorp/logutils']
    version = 'v1.0.0'
    hash = 'sha256-e8t8Dm8sp/PzKClN1TOmFcrTAWNh4mZHSW7cAjVx3Bw='

  [mod.'github.com/hashicorp/terraform-exec']
    version = 'v0.24.0'
    hash = 'sha256-PAJ+ZFGKlf5tYLUeOHJqM01iB5ymlv1m/ZilTi3fZy0='

  [mod.'github.com/hashicorp/terraform-json']
    version = 'v0.27.2'
    hash = 'sha256-sU3piJG6/f/Ig9uOgz0WEtreh0edr7WfOuGAe27YV5k='

  [mod.'github.com/hashicorp/terraform-plugin-go']
    version = 'v0.29.0'
    hash = 'sha256-xw5zqUNQCpnIPjoHcpPc0eZgfud+skpqpoC2q58CkOE='

  [mod.'github.com/hashicorp/terraform-plugin-log']
    version = 'v0.10.0'
    hash = 'sha256-3o7I8psZw6PC7IEcWth7kkV3Qvg6zEypqXCNY8pKHm0='

  [mod.'github.com/hashicorp/terraform-plugin-sdk/v2']
    version = 'v2.38.1'
    hash = 'sha256-Uob2XR5T06E2/z9YUA6Qu4FYUPAp6u8/DdqIECW8cHM='

  [mod.'github.com/hashicorp/terraform-plugin-testing']
    version = 'v1.14.0'
    hash = 'sha256-/UBngCMIF9ds6zpmlWZX4n7dgyNO4hmDasOIbxEYZMs='

  [mod.'github.com/hashicorp/terraform-registry-address']
    version = 'v0.4.0'
    hash = 'sha256-OXq27JNuMvQJG3rJA++oidAUgkx/FqRUy85CTrRO2oQ='

  [mod.'github.com/hashicorp/terraform-svchost']
    version = 'v0.1.1'
    hash = 'sha256-kY0Dcmr4CXHaSx1keJrEfsgsxYhxh8Abh5kicmlZDGQ='

  [mod.'github.com/hashicorp/yamux']
    version = 'v0.1.2'
    hash = 'sha256-JvpgwhqKAaS0PSlU/obe4tDJ2LcR1pyWRmJTkmT7hrA='

  [mod.'github.com/kylelemons/godebug']
    version = 'v1.1.0'
    hash = 'sha256-DJ0re9mGqZb6PROQI8NPC0JVyDHdZ/y4uehNH7MbczY='

  [mod.'github.com/mattn/go-colorable']
    version = 'v0.1.13'
    hash = 'sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/microsoft/azure-devops-go-api/azuredevops/v7']
    version = 'v7.0.0-20250711060739-8a0bc4f93533'
    hash = 'sha256-84+kE16XjezA5YiUJJJwSi343lxvbaI6/aYLP/J9PSc='
    replaced = 'github.com/magodo/azure-devops-go-api/azuredevops/v7'

  [mod.'github.com/mitchellh/copystructure']
    version = 'v1.2.0'
    hash = 'sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc='

  [mod.'github.com/mitchellh/go-testing-interface']
    version = 'v1.14.1'
    hash = 'sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c='

  [mod.'github.com/mitchellh/go-wordwrap']
    version = 'v1.0.1'
    hash = 'sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo='

  [mod.'github.com/mitchellh/mapstructure']
    version = 'v1.5.0'
    hash = 'sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE='

  [mod.'github.com/mitchellh/reflectwalk']
    version = 'v1.0.2'
    hash = 'sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s='

  [mod.'github.com/oklog/run']
    version = 'v1.1.0'
    hash = 'sha256-U4IS0keJa4BSBSeEBqtIV1Zg6N4b0zFiKfzN9ua4pWQ='

  [mod.'github.com/pkg/browser']
    version = 'v0.0.0-20240102092130-5ac0b6a4141c'
    hash = 'sha256-9iaSHHpcA1fXVF5f8RlKyo1DSoHx7eGXIC2/4LFaoBY='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/stretchr/testify']
    version = 'v1.10.0'
    hash = 'sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI='

  [mod.'github.com/vmihailenco/msgpack']
    version = 'v4.0.4+incompatible'
    hash = 'sha256-gA3l8Ma1XVja+C8XJzgRTQVb1htbsh4yrbnOu6cuw9U='

  [mod.'github.com/vmihailenco/msgpack/v5']
    version = 'v5.4.1'
    hash = 'sha256-pDplX6xU6UpNLcFbO1pRREW5vCnSPvSU+ojAwFDv3Hk='

  [mod.'github.com/vmihailenco/tagparser/v2']
    version = 'v2.0.0'
    hash = 'sha256-M9QyaKhSmmYwsJk7gkjtqu9PuiqZHSmTkous8VWkWY0='

  [mod.'github.com/zclconf/go-cty']
    version = 'v1.17.0'
    hash = 'sha256-4sNzbFwMnx+O0bULL7Ww73MaOnWIzJ3EMPvP/EwdNwA='

  [mod.'go.uber.org/mock']
    version = 'v0.5.0'
    hash = 'sha256-OLgbIRFUgt2taXypu5zSfnUZeeevNaU/myCdXBOBVaA='

  [mod.'golang.org/x/crypto']
    version = 'v0.54.0'
    hash = 'sha256-m8jsqlPuoPxGDjClzcAVbXf1aiU07L+9j7vYcqJu/0Q='

  [mod.'golang.org/x/mod']
    version = 'v0.37.0'
    hash = 'sha256-dspScRv3KO4nytvjavhNO2b03P4UtiJQyWVGuEy9OUk='

  [mod.'golang.org/x/net']
    version = 'v0.56.0'
    hash = 'sha256-JUORjxDZqZanYWo2yunaDpQ2/zvHiFb0TnF1Jw6D+30='

  [mod.'golang.org/x/sync']
    version = 'v0.22.0'
    hash = 'sha256-VZjl0fAM0p/nI81zh+pdBjzxFupx0UcKYXBBpL2ZS7k='

  [mod.'golang.org/x/sys']
    version = 'v0.47.0'
    hash = 'sha256-TpbRyWWqHjddP6QzUgAbaLd2EE0S+GYNRUIDJd18r98='

  [mod.'golang.org/x/text']
    version = 'v0.40.0'
    hash = 'sha256-LJfnki46XEreGbSgjl+DeqgcTsINTOu2owyXNvijMcA='

  [mod.'golang.org/x/tools']
    version = 'v0.47.0'
    hash = 'sha256-LyCNqEb/Jm94O6gaM01vXSHP9Yw/Cw0qVWXGxhCgwzo='

  [mod.'google.golang.org/appengine']
    version = 'v1.6.8'
    hash = 'sha256-decMa0MiWfW/Bzr8QPPzzpeya0YWGHhZAt4Cr/bD1wQ='

  [mod.'google.golang.org/genproto/googleapis/rpc']
    version = 'v0.0.0-20251202230838-ff82c1b0f217'
    hash = 'sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA='

  [mod.'google.golang.org/grpc']
    version = 'v1.79.3'
    hash = 'sha256-mO9ZI8ONBMEBTlrwIPeQMfb3C9ru5zPb26P+uG/pIzY='

  [mod.'google.golang.org/protobuf']
    version = 'v1.36.10'
    hash = 'sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
