name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: thecluster
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: unmango/actions/setup-nix@3ec4ed5a6af9c00f6a39e079df488573c77ebda6 # v1.0.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # `checks` contains every package, so this builds the whole package set.
      - run: nix flake check --print-build-logs
